import React from "react";
import Head from "next/head";
import Hero from "../components/Hero";
import Portfolio from "../components/Portfolio";

const work = () => {
  return (
    <div>
      <Head>
        <title>Portfolio Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='My Work' message="View Victor Kimura's portfolio work" />
      <Portfolio />
    </div>
  );
};

export default work;
